add_newline = false
command_timeout = 1000
scan_timeout = 1000

[aws]
disabled = true
style = "bold #ffb86c"

# [aws.region_aliases]
# us-east-1 = "va"

[battery]
disabled = true

[bun]
disabled = true

[character]
error_symbol = "[âœ—](bold #ff5555)"
success_symbol = "[âœ](bold #50fa7b)"
# dracula style...
# error_symbol = "[Î»](bold #ff5555)"
# success_symbol = "[Î»](bold #50fa7b)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

# [direnv]
# disabled = true

# [docker_context]
# # disabled = false
# # only_with_files = false
# symbol = "ğŸ³ "

[git_branch]
style = "bold #ff79c6"
symbol = "î‚  "

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"

[kubernetes]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"

[custom.just]
description = "Checks for justfile"
command = "echo ğŸ§ƒ"
when = 'test -f justfile || test -f Justfile || test -d .justfiles'
style = "bold green"
